bump: Bump of CDC to 0.27
OpenSourcePolitics/decidim-cdc pull request #41
Opened 2024-07-05 10:20 UTC by AyakorK

#### :tophat: Description
*Please describe your pull request.*
Bump of CDC to 0.27 (based on master because had some pushes that were more recents than develop)
We need to ensure that the main custo (SAML SSO) is still available and than this bump didn't got rid of it)

#### :pushpin: Related Issues
*Link your PR to an issue*
- [Cour des comptes - Montée de version 0.27](https://www.notion.so/opensourcepolitics/Cour-des-comptes-Mont-e-de-version-0-27-889baef0c142421d8f120279717b47d9?pvs=4)

#### Tasks
- [ ] Bump to 0.27.5 (compatibility issue in 0.27.6 we need to check this afterwards for every instance)
- [ ] Modify files and update them to the release/0.27-stable of decidim
- [ ] Update the CI and add the zeitwerk check
- [ ] Update the Dockerfile to ensure that it works everytime (based it from the dcd-app)
- [ ] Update the profile to add some fixes related to the tests
- [ ] Add missing locales
- [ ] Global rubocop refactor

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2024-07-08 07:53 UTC, Quentinchampenois requested changes
Just a backport needed otherwise it looks great !

2024-07-08 07:53 UTC, Quentinchampenois commented on Makefile
> +up:
Can you backport this PR on the bump ? 
https://github.com/OpenSourcePolitics/decidim-app/pull/554/files

2024-07-08 12:21 UTC, BarbaraOliveira13 approved these changes
I ran It. Everything works 🎉  (sign in, sign up, proposals, reviews, & notifications...) except for one thing: I just noticed that the awesome-map displays nothing in my app locally.
![Uploading Capture d’écran 2024-07-08 à 14.01.41.png…]()
.
<img width="1176" alt="Capture d’écran 2024-07-08 à 13 58 43" src="https://github.com/OpenSourcePolitics/decidim-cdc/assets/143180473/117ba6a5-b7ba-4e37-bf55-a88de1f4bb9a">
<img width="1130" alt="Capture d’écran 2024-07-08 à 14 01 41" src="https://github.com/OpenSourcePolitics/decidim-cdc/assets/143180473/8c3401b9-7d5f-4eb4-a0c1-d2927c7239b4">

2024-07-08 16:12 UTC, AyakorK commented
Hey Barbara ! Thanks for the feedback ! 

I may be wrong but it does not display anything probably because you don't have the env var to activate the API locally, which may cause this issue.

If you think that it's not the cause and that's a real issue then don't mind telling me again ! I'll work on it afterwards !

2024-07-12 09:21 UTC, Quentinchampenois approved these changes

2024-07-15 07:27 UTC, luciegrau approved these changes

2024-07-15 07:28 UTC, merged